### ISSUE TITLE
It won't install if Atom isn't installed already

### ISSUE THREAD

**Issue by innovara** [DokterW/SHatomATOR#1]
It won't install if Atom isn't installed already.

$ATOMLATEST is defined within if [[ -e /bin/atom ]] therefore it will be undefined when you reach the else statement and "wget -q --show-progress $ATOMDOWNLOAD$ATOMLATEST/$ATOMRPM -P /tmp/" will not retrieve the correct URL as the version number is missing.

**Comment by innovara** [comment]
Oh, and thank you for the script, it works great after the adjustment

**Comment by DokterW** [comment]
Hi,

Glad you liked it! Just something I smashed together out of laziness. As in, being too lazy to check the website.

I already had Atom installed, but haven't used the script since I reinstalled my laptop. It worked as expected. If you already have it installed it should perform the version check. If binary not found, then it'll just install.

Please clarify if I missed something.

**Comment by innovara** [comment]
Sorry about the double pull request. I'm still learning how git works to be honest.
The issue is that the else statement that installs Atom will be executed when the fist if statement isn't, where you define ATOMLATEST, so it will be undefined in the former

**Comment by DokterW** [comment]
Hi, I had a closer look now and you're absolutely right!
I also found a redundant variable.
Thanks for the feedback! Much Appreciated!
